
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give permission to Gradle
        run: chmod +x MessageCounterAppFull/gradlew

      - name: Build debug APK
        run: MessageCounterAppFull/gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: MessageCounterAppFull/app/build/outputs/apk/debug/app-debug.apk

