name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # This is the final, definitive build step
      - name: Build with Gradle (No Cache)
        uses: gradle/gradle-build-action@v2
        with:
          # Tell the action to ignore all caches
          cache-disabled: true
          # Tell Gradle to clean before building
          arguments: clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: message-counter-apk
          path: app/build/outputs/apk/debug/app-debug.apk